version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-bookmark
    ports:
      - 5432:5432
    networks:
      - freecodecamp
networks:
  freecodecamp:
